import type { Product, ProductCategory } from "../types/product"

export const productCategories: ProductCategory[] = [
  {
    id: "fruits-vegetables",
    name: "Fruits & Vegetables",
    nameAr: "الفواكه والخضروات",
    icon: "apple",
    subcategories: [
      { id: "fresh-fruits", name: "Fresh Fruits", nameAr: "فواكه طازجة", categoryId: "fruits-vegetables" },
      { id: "fresh-vegetables", name: "Fresh Vegetables", nameAr: "خضروات طازجة", categoryId: "fruits-vegetables" },
      { id: "herbs", name: "Herbs", nameAr: "أعشاب", categoryId: "fruits-vegetables" },
      { id: "organic-produce", name: "Organic Produce", nameAr: "منتجات عضوية", categoryId: "fruits-vegetables" },
    ],
  },
  {
    id: "dairy-eggs",
    name: "Dairy & Eggs",
    nameAr: "منتجات الألبان والبيض",
    icon: "milk",
    subcategories: [
      { id: "milk", name: "Milk", nameAr: "حليب", categoryId: "dairy-eggs" },
      { id: "cheese", name: "Cheese", nameAr: "جبن", categoryId: "dairy-eggs" },
      { id: "yogurt", name: "Yogurt", nameAr: "زبادي", categoryId: "dairy-eggs" },
      { id: "butter", name: "Butter & Margarine", nameAr: "زبدة ومارجرين", categoryId: "dairy-eggs" },
      { id: "eggs", name: "Eggs", nameAr: "بيض", categoryId: "dairy-eggs" },
      { id: "vegan-dairy", name: "Vegan Alternatives", nameAr: "بدائل نباتية", categoryId: "dairy-eggs" },
    ],
  },
  {
    id: "meat-seafood",
    name: "Meat & Seafood",
    nameAr: "اللحوم والمأكولات البحرية",
    icon: "beef",
    subcategories: [
      { id: "beef", name: "Beef", nameAr: "لحم بقري", categoryId: "meat-seafood" },
      { id: "poultry", name: "Poultry", nameAr: "دواجن", categoryId: "meat-seafood" },
      { id: "pork", name: "Pork", nameAr: "لحم خنزير", categoryId: "meat-seafood" },
      { id: "lamb", name: "Lamb", nameAr: "لحم ضأن", categoryId: "meat-seafood" },
      { id: "fish", name: "Fish", nameAr: "سمك", categoryId: "meat-seafood" },
      { id: "shellfish", name: "Shellfish", nameAr: "محار", categoryId: "meat-seafood" },
      { id: "plant-based", name: "Plant-Based", nameAr: "بدائل نباتية", categoryId: "meat-seafood" },
    ],
  },
  {
    id: "bakery",
    name: "Bakery",
    nameAr: "مخبوزات",
    icon: "bread",
    subcategories: [
      { id: "bread", name: "Bread", nameAr: "خبز", categoryId: "bakery" },
      { id: "pastries", name: "Pastries", nameAr: "معجنات", categoryId: "bakery" },
      { id: "cakes", name: "Cakes", nameAr: "كيك", categoryId: "bakery" },
      { id: "cookies", name: "Cookies", nameAr: "بسكويت", categoryId: "bakery" },
      { id: "gluten-free", name: "Gluten-Free", nameAr: "خالي من الغلوتين", categoryId: "bakery" },
    ],
  },
  {
    id: "beverages",
    name: "Beverages",
    nameAr: "مشروبات",
    icon: "coffee",
    subcategories: [
      { id: "water", name: "Water", nameAr: "ماء", categoryId: "beverages" },
      { id: "juice", name: "Juice", nameAr: "عصير", categoryId: "beverages" },
      { id: "soda", name: "Soda", nameAr: "صودا", categoryId: "beverages" },
      { id: "coffee", name: "Coffee", nameAr: "قهوة", categoryId: "beverages" },
      { id: "tea", name: "Tea", nameAr: "شاي", categoryId: "beverages" },
      { id: "alcohol", name: "Alcohol", nameAr: "كحول", categoryId: "beverages" },
    ],
  },
  {
    id: "snacks",
    name: "Snacks",
    nameAr: "وجبات خفيفة",
    icon: "cookie",
    subcategories: [
      { id: "chips", name: "Chips", nameAr: "رقائق", categoryId: "snacks" },
      { id: "nuts", name: "Nuts & Seeds", nameAr: "مكسرات وبذور", categoryId: "snacks" },
      { id: "chocolate", name: "Chocolate", nameAr: "شوكولاتة", categoryId: "snacks" },
      { id: "candy", name: "Candy", nameAr: "حلوى", categoryId: "snacks" },
      { id: "healthy-snacks", name: "Healthy Snacks", nameAr: "وجبات خفيفة صحية", categoryId: "snacks" },
    ],
  },
  {
    id: "pantry",
    name: "Pantry",
    nameAr: "مؤن",
    icon: "package",
    subcategories: [
      { id: "pasta-rice", name: "Pasta & Rice", nameAr: "معكرونة وأرز", categoryId: "pantry" },
      { id: "canned-goods", name: "Canned Goods", nameAr: "معلبات", categoryId: "pantry" },
      { id: "sauces", name: "Sauces & Condiments", nameAr: "صلصات وتوابل", categoryId: "pantry" },
      { id: "spices", name: "Spices & Seasonings", nameAr: "بهارات وتوابل", categoryId: "pantry" },
      { id: "baking", name: "Baking Essentials", nameAr: "مستلزمات الخبز", categoryId: "pantry" },
      { id: "oils", name: "Oils & Vinegars", nameAr: "زيوت وخل", categoryId: "pantry" },
    ],
  },
  {
    id: "frozen",
    name: "Frozen Foods",
    nameAr: "أطعمة مجمدة",
    icon: "snowflake",
    subcategories: [
      { id: "frozen-meals", name: "Frozen Meals", nameAr: "وجبات مجمدة", categoryId: "frozen" },
      { id: "frozen-pizza", name: "Frozen Pizza", nameAr: "بيتزا مجمدة", categoryId: "frozen" },
      { id: "frozen-vegetables", name: "Frozen Vegetables", nameAr: "خضروات مجمدة", categoryId: "frozen" },
      { id: "frozen-fruits", name: "Frozen Fruits", nameAr: "فواكه مجمدة", categoryId: "frozen" },
      { id: "ice-cream", name: "Ice Cream", nameAr: "آيس كريم", categoryId: "frozen" },
    ],
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Organic Bananas",
    nameAr: "موز عضوي",
    description: "Sweet and fresh organic bananas, perfect for smoothies or a healthy snack.",
    descriptionAr: "موز عضوي حلو وطازج، مثالي للعصائر أو وجبة خفيفة صحية.",
    price: 1.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "fruits-vegetables",
    subcategoryId: "fresh-fruits",
    tags: ["organic", "vegan"],
    rating: 4.8,
    ratingCount: 245,
    stock: 150,
    unit: "bunch",
    weight: 1.2,
    nutritionInfo: {
      calories: 105,
      protein: 1.3,
      carbs: 27,
      fat: 0.4,
      fiber: 3.1,
      sugar: 14,
    },
    ingredients: ["Organic Bananas"],
    isFavorite: false,
    isPopular: true,
    storeId: "s1",
  },
  {
    id: "p2",
    name: "Fresh Avocados",
    nameAr: "أفوكادو طازج",
    description: "Creamy and ripe avocados, perfect for guacamole or avocado toast.",
    descriptionAr: "أفوكادو كريمي وناضج، مثالي للجواكامولي أو توست الأفوكادو.",
    price: 2.49,
    originalPrice: 2.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "fruits-vegetables",
    subcategoryId: "fresh-fruits",
    tags: ["organic", "vegan"],
    rating: 4.6,
    ratingCount: 189,
    stock: 75,
    unit: "piece",
    weight: 0.2,
    nutritionInfo: {
      calories: 160,
      protein: 2,
      carbs: 9,
      fat: 15,
      fiber: 7,
    },
    ingredients: ["Organic Avocados"],
    isFavorite: true,
    isPopular: true,
    discount: 17,
    storeId: "s1",
  },
  {
    id: "p3",
    name: "Whole Milk",
    nameAr: "حليب كامل الدسم",
    description: "Fresh whole milk from grass-fed cows, rich and creamy.",
    descriptionAr: "حليب طازج كامل الدسم من أبقار تتغذى على العشب، غني وكريمي.",
    price: 3.49,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "dairy-eggs",
    subcategoryId: "milk",
    tags: ["local"],
    rating: 4.7,
    ratingCount: 312,
    stock: 50,
    unit: "gallon",
    nutritionInfo: {
      calories: 150,
      protein: 8,
      carbs: 12,
      fat: 8,
    },
    ingredients: ["Whole Milk"],
    isFavorite: false,
    storeId: "s2",
  },
  {
    id: "p4",
    name: "Organic Eggs",
    nameAr: "بيض عضوي",
    description: "Farm-fresh organic eggs from free-range chickens.",
    descriptionAr: "بيض عضوي طازج من المزرعة من دجاج طليق.",
    price: 4.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "dairy-eggs",
    subcategoryId: "eggs",
    tags: ["organic", "local"],
    rating: 4.9,
    ratingCount: 178,
    stock: 30,
    unit: "dozen",
    nutritionInfo: {
      calories: 70,
      protein: 6,
      carbs: 0,
      fat: 5,
    },
    ingredients: ["Organic Eggs"],
    isFavorite: true,
    isNew: true,
    storeId: "s1",
  },
  {
    id: "p5",
    name: "Sourdough Bread",
    nameAr: "خبز العجين المخمر",
    description: "Artisanal sourdough bread, freshly baked with a perfect crust.",
    descriptionAr: "خبز العجين المخمر الحرفي، مخبوز طازجًا بقشرة مثالية.",
    price: 5.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "bakery",
    subcategoryId: "bread",
    tags: ["vegan", "local"],
    rating: 4.8,
    ratingCount: 156,
    stock: 20,
    unit: "loaf",
    weight: 0.8,
    nutritionInfo: {
      calories: 120,
      protein: 4,
      carbs: 20,
      fat: 1,
      fiber: 2,
    },
    ingredients: ["Organic Flour", "Water", "Salt", "Sourdough Starter"],
    isFavorite: false,
    isPopular: true,
    storeId: "s3",
  },
  {
    id: "p6",
    name: "Grass-Fed Ground Beef",
    nameAr: "لحم بقر مفروم من أبقار تتغذى على العشب",
    description: "Premium grass-fed ground beef, perfect for burgers and meatballs.",
    descriptionAr: "لحم بقر مفروم ممتاز من أبقار تتغذى على العشب، مثالي للبرغر وكرات اللحم.",
    price: 8.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "meat-seafood",
    subcategoryId: "beef",
    tags: ["local"],
    rating: 4.7,
    ratingCount: 203,
    stock: 25,
    unit: "lb",
    weight: 1,
    nutritionInfo: {
      calories: 250,
      protein: 26,
      carbs: 0,
      fat: 17,
    },
    ingredients: ["100% Grass-Fed Beef"],
    isFavorite: false,
    storeId: "s2",
  },
  {
    id: "p7",
    name: "Organic Spinach",
    nameAr: "سبانخ عضوية",
    description: "Fresh organic spinach, washed and ready to eat.",
    descriptionAr: "سبانخ عضوية طازجة، مغسولة وجاهزة للأكل.",
    price: 3.99,
    originalPrice: 4.99,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "fruits-vegetables",
    subcategoryId: "fresh-vegetables",
    tags: ["organic", "vegan"],
    rating: 4.5,
    ratingCount: 132,
    stock: 40,
    unit: "bag",
    weight: 0.3,
    nutritionInfo: {
      calories: 20,
      protein: 2,
      carbs: 3,
      fat: 0,
      fiber: 2,
    },
    ingredients: ["Organic Spinach"],
    isFavorite: true,
    discount: 20,
    storeId: "s1",
  },
  {
    id: "p8",
    name: "Almond Milk",
    nameAr: "حليب اللوز",
    description: "Unsweetened almond milk, dairy-free and low in calories.",
    descriptionAr: "حليب اللوز غير المحلى، خالي من منتجات الألبان ومنخفض السعرات الحرارية.",
    price: 3.49,
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    thumbnail: "/placeholder.svg?height=200&width=200",
    categoryId: "dairy-eggs",
    subcategoryId: "vegan-dairy",
    tags: ["vegan", "dairy-free"],
    rating: 4.6,
    ratingCount: 178,
    stock: 35,
    unit: "carton",
    nutritionInfo: {
      calories: 30,
      protein: 1,
      carbs: 1,
      fat: 2.5,
    },
    ingredients: ["Filtered Water", "Almonds", "Calcium Carbonate", "Sea Salt"],
    isFavorite: false,
    isNew: true,
    storeId: "s3",
  },
]
